In [1]:
import numpy as np

In [2]:
arr = np.array([])
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


In [3]:
print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)


array: 
 []
arr.data:  <memory at 0x0000027AC6868B80>
arr.shape:  (0,)
arr.dtype:  float64
arr.size:  0
arr.itemsize:  8
arr.nbytes:  0
arr.strides:  (8,)


In [6]:
my_list = [1,2,3,4,5,6,7,8]
arr = np.array(my_list,dtype = np.int8)

print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)


array: 
 [1 2 3 4 5 6 7 8]
arr.data:  <memory at 0x0000027AC6905040>
arr.shape:  (8,)
arr.dtype:  int8
arr.size:  8
arr.itemsize:  1
arr.nbytes:  8
arr.strides:  (1,)


In [11]:
my_list_2 = [[1, 2, 3],[4, 5, 6],[7, 8, 9],[11, 12, 13]]
arr = np.array(my_list_2, dtype = np.complex64)

print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)


array: 
 [[ 1.+0.j  2.+0.j  3.+0.j]
 [ 4.+0.j  5.+0.j  6.+0.j]
 [ 7.+0.j  8.+0.j  9.+0.j]
 [11.+0.j 12.+0.j 13.+0.j]]
arr.data:  <memory at 0x0000027AC6789040>
arr.shape:  (4, 3)
arr.dtype:  complex64
arr.size:  12
arr.itemsize:  8
arr.nbytes:  96
arr.strides:  (24, 8)


In [13]:
mylist = [
          [[1, 2, 3], [5, 6, 7], [3, 2, 4]],
          [[8, 1, 6], [1, 9, 4], [5, 6, 4]],
          [[5, 3, 2], [2, 0, 5], [8, 3, 0]],
          [[6, 7, 1], [8, 1, 6], [1, 4, 7]],
          [[2, 8, 9], [3, 0, 4], [5, 2, 2]],
         ]
arr = np.array(mylist, dtype=np.uint8)


print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)

array: 
 [[[1 2 3]
  [5 6 7]
  [3 2 4]]

 [[8 1 6]
  [1 9 4]
  [5 6 4]]

 [[5 3 2]
  [2 0 5]
  [8 3 0]]

 [[6 7 1]
  [8 1 6]
  [1 4 7]]

 [[2 8 9]
  [3 0 4]
  [5 2 2]]]
arr.data:  <memory at 0x0000027AC67BAC70>
arr.shape:  (5, 3, 3)
arr.dtype:  uint8
arr.size:  45
arr.itemsize:  1
arr.nbytes:  45
arr.strides:  (9, 3, 1)


In [14]:
arr = np.zeros(3) #1D array of zeros

In [15]:
arr#by default dtype is float

array([0., 0., 0.])

In [17]:
arr = np.zeros((3,2), dtype = np.int8) #2D array with dtype int
arr

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [27]:
arr = np.zeros(3,3,3) 
arr

TypeError: Cannot interpret '3' as a data type

In [24]:
arr = np.ones((3,2,4),dtype = np.int8)
arr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

In [3]:
arr = np.full(2,1)
arr

array([1, 1])

In [18]:
arr = np.full((3,2,3),21)
arr

array([[[21, 21, 21],
        [21, 21, 21]],

       [[21, 21, 21],
        [21, 21, 21]],

       [[21, 21, 21],
        [21, 21, 21]]])

In [9]:
dia_arr = np.eye(3,3,k = 0 ,dtype = int)
dia_arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
dia_arr = np.eye(3,2,k = -2, dtype =int)
dia_arr

array([[0, 0],
       [0, 0],
       [1, 0]])

In [17]:
arr = np.fromstring('12,13,15', sep = ',', dtype = np.int8)
arr

array([12, 13, 15], dtype=int8)

In [25]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [28]:
arr = np.arange(2,7)
arr

array([2, 3, 4, 5, 6])

In [32]:
arr =np.linspace(1,9, num =3, dtype =int)
arr

array([1, 5, 9])

In [35]:
arr = np.random.rand(3,4)
arr

array([[0.24019179, 0.18993862, 0.56778195, 0.32405216],
       [0.71818684, 0.03294649, 0.44799065, 0.36779372],
       [0.09729271, 0.33173098, 0.82002839, 0.17531234]])

In [37]:
arr = np.random.randint(low =4, high = 10, size =2)
arr

array([7, 9])