In [3]:
import numpy as np

In [4]:
arr1 = np.linspace(5,10)
print(arr1)

[ 5.          5.10204082  5.20408163  5.30612245  5.40816327  5.51020408
  5.6122449   5.71428571  5.81632653  5.91836735  6.02040816  6.12244898
  6.2244898   6.32653061  6.42857143  6.53061224  6.63265306  6.73469388
  6.83673469  6.93877551  7.04081633  7.14285714  7.24489796  7.34693878
  7.44897959  7.55102041  7.65306122  7.75510204  7.85714286  7.95918367
  8.06122449  8.16326531  8.26530612  8.36734694  8.46938776  8.57142857
  8.67346939  8.7755102   8.87755102  8.97959184  9.08163265  9.18367347
  9.28571429  9.3877551   9.48979592  9.59183673  9.69387755  9.79591837
  9.89795918 10.        ]


In [5]:
arr1 = np.random.randint(1,50,size = 5)
print(arr1)

[16 10  5 42 41]


In [6]:
arr2 = np.random.randint(1,50,size =(2,3))
print(arr2)

[[14 24 48]
 [29 17 35]]


In [7]:
print(arr2.strides)

(12, 4)


In [8]:
print(arr2.dtype)

int32


In [16]:
np.resize = (arr2,(3,2))

In [10]:
arr2

array([[14, 24],
       [48, 29],
       [17, 35]])

In [17]:
np.resize

(array([[14, 24],
        [48, 29],
        [17, 35]]),
 (3, 2))