In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,5,6,7,8]
arr = np.array(list1)
print(arr)
print(arr.shape)
print(arr.strides)

[1 2 3 5 6 7 8]
(7,)
(4,)


In [3]:
arr[0:2]

array([1, 2])

In [4]:
arr2 = arr[-1:-6:-2]
arr2

array([8, 6, 3])

In [5]:
arr[:]


array([1, 2, 3, 5, 6, 7, 8])

In [6]:
arr[::-1]

array([8, 7, 6, 5, 3, 2, 1])

In [7]:
list1 = [[1,2],[3,5],[6,7]]
arr = np.array(list1)
print(arr)
print(arr.shape)
print(arr.strides)

[[1 2]
 [3 5]
 [6 7]]
(3, 2)
(8, 4)


In [8]:
arr[1]

array([3, 5])

In [9]:
arr[:]

array([[1, 2],
       [3, 5],
       [6, 7]])

In [10]:
arr[1:2]

array([[3, 5]])

In [11]:
arr[1:2,:]

array([[3, 5]])

In [12]:
arr[1,0]

3

In [13]:
arr[::-1]

array([[6, 7],
       [3, 5],
       [1, 2]])

In [14]:
arr[::,::-1]

array([[2, 1],
       [5, 3],
       [7, 6]])

In [15]:
m1 = np.array([
            [0,1,2,3,4,5],
            [6,7,8,9,10,11],
            [12,13,14,15,16,17],
            [18,19,20,21,22,23],
            [24,25,26,27,28,29],
            [30,31,32,33,34,35]
])

In [16]:
m1[2:5]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [17]:
m1[0,2:5]

array([2, 3, 4])

In [42]:
m1[:,2]

array([ 2,  8, 14, 20, 26, 32])

In [44]:
print(m1[:,:])
m1[2::2,0::2]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[12, 14, 16],
       [24, 26, 28]])

In [22]:
print(m1.shape)

(6, 6)


In [24]:
m1[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [26]:
m1[::-1,::]

array([[30, 31, 32, 33, 34, 35],
       [24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [27]:
m1[::,::-1]

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24],
       [35, 34, 33, 32, 31, 30]])

In [28]:
m1[0,0]

0

In [32]:
m1[::,1]

array([ 1,  7, 13, 19, 25, 31])

In [33]:
m1[1]

array([ 6,  7,  8,  9, 10, 11])

In [35]:
m1[:,1]

array([ 1,  7, 13, 19, 25, 31])

In [29]:
import numpy as np
mylist = [
          [[1, 2, 3], [5, 6, 7], [9, 0, 5], [2,3,4]],
          [[8, 1, 6], [1, 9, 4], [5, 8, 2], [3,4,4]],
          [[2, 3, 4], [1, 2, 3], [2, 5, 6], [2,3, 4]]
         ]
arr = np.array(mylist)
print("Original Array:\n", arr)
print("Array Shape = ",arr.shape)
print("Strides:", arr.strides)


Original Array:
 [[[1 2 3]
  [5 6 7]
  [9 0 5]
  [2 3 4]]

 [[8 1 6]
  [1 9 4]
  [5 8 2]
  [3 4 4]]

 [[2 3 4]
  [1 2 3]
  [2 5 6]
  [2 3 4]]]
Array Shape =  (3, 4, 3)
Strides: (48, 12, 4)


In [31]:
arr[1][2][0]

5

In [46]:
#fancy Index#

In [47]:
arr = np.random.randint(1,100,10)
print (arr)
print (arr[np.array([0,2,4,6])])

[31 80 76 72 23 48 90 42  6 10]
[31 76 23 90]


In [49]:
print(arr[[0,2,4,6]])

[31 76 23 90]


In [50]:
# Boolean Indexing
import numpy as np
# creating 1-D array of size 10 of int type b/w interval (1,100) 
arr = np.random.randint(1, 101, 10)
print("Original Array: ", arr)

# Getting even values from array
print("\narr[arr%2 == 0] = ",arr[arr%2==0])
# Getting odd values from array
print("arr[arr%2 == 1] = ",arr[arr%2==1])

# Getting values greater than 50
print("\narr[arr > 50] = ",arr[arr > 50])
# Getting values between 25 and 75 both exclusive
print("arr[arr>30 & arr<60] = ",arr[(arr>30) & (arr<60)])

Original Array:  [ 52 100  39  96  99  90  94  31  31  35]

arr[arr%2 == 0] =  [ 52 100  96  90  94]
arr[arr%2 == 1] =  [39 99 31 31 35]

arr[arr > 50] =  [ 52 100  96  99  90  94]
arr[arr>30 & arr<60] =  [52 39 31 31 35]
